### ISSUE TITLE
PropertyType

### ISSUE THREAD

**Issue by egch** [your-rents/your-rents-api#5]
### PropertyType Lookup Table

The `PropertyType` table is used to define valid property types for the `Property` entity. This ensures data consistency and allows easy additions or updates to property classifications.

| **ID** | **Name**     | **Description**               | **Code**  |
|--------|--------------|-------------------------------|-----------|
| 1      | Flat         | A single unit in a building.  | FLAT      |
| 2      | House        | A standalone property.        | HOUSE     |
| 3      | Studio       | A small, single-room flat.    | STUDIO    |
| 4      | Villa        | A luxurious standalone house. | VILLA     |
| 5      | Commercial   | Space for business purposes.  | COMMERCIAL|

---

### PropertyType Table

| **Column**     | **Type** | **Description**                                 |
|-----------------|----------|-----------------------------------------------|
| `external_id`           | UUID     | Primary business key.                                   |
| `name`         | String   | Name of the property type (e.g., "Flat").      |
| `description`  | String   | (Optional) Detailed description.               |
| `code`         | String   | (Optional) Unique identifier (e.g., "FLAT").   |

```mermaid
---
title: PropertyType relationship
---
classDiagram
    class Property {
        propertyTypeUuid: UUID
    }

    class PropertyType {
        external_id: UUID
    }

    Property "1" --> "0..*" PropertyType : belongs to
```

**Comment by benfante** [comment]
For internal relationship (foreign keys), I would like to have numeric ids, not UUIDs. I want to use UUIDs only for external references.
